# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CSCORE_IRLS_cpp_impl <- function(X, seq_depth_sq, D_mu, D_sigma2, D_sigma, post_process = TRUE, n_iter = 10L, eps = 0.05, verbose = FALSE, conv = "q95", return_all = FALSE) {
    .Call(`_CSCORE_CSCORE_IRLS_cpp_impl`, X, seq_depth_sq, D_mu, D_sigma2, D_sigma, post_process, n_iter, eps, verbose, conv, return_all)
}

WLS_cov <- function(D, X, W) {
    .Call(`_CSCORE_WLS_cov`, D, X, W)
}

WLS_mean <- function(D, X, W) {
    .Call(`_CSCORE_WLS_mean`, D, X, W)
}

