# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WLS_mean <- function(D, X, W) {
    .Call('_CSCORE_WLS_mean', PACKAGE = 'CSCORE', D, X, W)
}

WLS_cov <- function(D, X, W) {
    .Call('_CSCORE_WLS_cov', PACKAGE = 'CSCORE', D, X, W)
}

