name: Windows (R-release)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::pak
          needs: check
      - name: Ensure latest Rcpp/RcppArmadillo
        run: |
          Rscript -e "pak::pkg_install(c('Rcpp','RcppArmadillo'))"
      - name: Check package
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          Rscript -e "rcmdcheck::rcmdcheck('.', args=c('--no-manual','--as-cran'), error_on='error')"
